"""Canonical LaTeX and formula normalization utilities.

Cleans and standardizes LaTeX expressions generated by OCR/layout parsers
(e.g., MinerU, Docling, Nougat) to improve consistency and maximize syntactic
alignment with ground-truth evaluations (such as Levenshtein edit distance).
"""

from __future__ import annotations

import re
from typing import Any

# Operators around which spacing should be standardized
_OPERATORS = (
    "+", "-", "=", "<", ">", r"\le", r"\ge", r"\ne",
    r"\times", r"\div", r"\approx", r"\pm",
)

# Regex to match leading and trailing equation delimiters ($$, $, \[, \], \(, \))
_DELIM_PREFIX_RE = re.compile(r"^(?:\$\$|\$|\\\[|\\\()\s*")
_DELIM_SUFFIX_RE = re.compile(r"\s*(?:\$\$|\$|\\\]|\\\))$")

# Regex to find unnecessary \text{} wrappers containing only single letters or numbers
_SIMPLE_TEXT_RE = re.compile(r"\\text\s*\{\s*([a-zA-Z0-9])\s*\}")

# Regex to collapse multiple spaces into one
_MULTI_SPACE_RE = re.compile(r"[ \t]+")

# Regex for subscript/superscript with redundant spacing: x   ^  {  2  } -> x^{2}
_SUPER_SUB_RE = re.compile(r"\s*([\^_])\s*\{\s*([^}]+?)\s*\}")


def strip_latex_delimiters(text: str) -> str:
    """Remove external LaTeX delimiters like $$, $, \\[, \\], \\(, \\)."""
    stripped = text.strip()
    for _ in range(3):
        prev = stripped
        stripped = _DELIM_PREFIX_RE.sub("", stripped)
        stripped = _DELIM_SUFFIX_RE.sub("", stripped)
        if stripped == prev:
            break
    return stripped.strip()


def normalize_latex(expr: str | None) -> str:
    """Normalize a LaTeX expression to canonical form.

    1. Strips external math delimiters ($$, $, etc.).
    2. Simplifies trivial `\\text{x}` into `x`.
    3. Normalizes exponents and subscripts: `x ^ { 2 }` -> `x^{2}`.
    4. Normalizes unicode math characters to standard LaTeX commands.
    5. Normalizes whitespace and operator spacing.
    """
    if not expr:
        return ""

    text = str(expr).strip()
    if not text:
        return ""

    # 1. Delimiters
    text = strip_latex_delimiters(text)

    # 2. Convert standard Unicode math symbols to LaTeX equivalents if present
    unicode_replacements = {
        "×": r"\times",  # noqa: RUF001
        "÷": r"\div",
        "±": r"\pm",
        "≤": r"\le",
        "≥": r"\ge",
        "≠": r"\ne",
        "≈": r"\approx",
        "∞": r"\infty",
        "α": r"\alpha",  # noqa: RUF001
        "β": r"\beta",
        "γ": r"\gamma",  # noqa: RUF001
        "θ": r"\theta",
        "π": r"\pi",
        "∑": r"\sum",
        "∏": r"\prod",
        "∫": r"\int",
        "√": r"\sqrt",
    }
    for char, latex_cmd in unicode_replacements.items():
        if char in text:
            text = text.replace(char, latex_cmd)

    # 3. Simplify trivial \text{} wrappers
    text = _SIMPLE_TEXT_RE.sub(r"\1", text)

    # 4. Normalize exponents and subscripts: `^ { 2 }` -> `^{2}`
    text = _SUPER_SUB_RE.sub(lambda m: f"{m.group(1)}{{{m.group(2).strip()}}}", text)

    # 5. Remove redundant spacing around brackets, braces, and parens
    text = re.sub(r"\(\s+", "(", text)
    text = re.sub(r"\s+\)", ")", text)
    text = re.sub(r"\{\s+", "{", text)
    text = re.sub(r"\s+\}", "}", text)
    text = re.sub(r"\[\s+", "[", text)
    text = re.sub(r"\s+\]", "]", text)

    # 6. Normalize operator spacing
    for op in ("=", r"\approx", r"\le", r"\ge", r"\ne"):
        pattern = rf"\s*{re.escape(op)}\s*"

        def _make_repl(o: str) -> Any:
            return lambda _: f" {o} "

        text = re.sub(pattern, _make_repl(op), text)

    for op in ("+", "-"):
        escaped_op = re.escape(op)
        pattern = r"(?<=[a-zA-Z0-9\}])\s*" + escaped_op + r"\s*(?=[a-zA-Z0-9{\\])"
        text = re.sub(pattern, _make_repl(op), text)

    # 7. Collapse multiple spaces
    text = _MULTI_SPACE_RE.sub(" ", text)

    # 8. Standardize linebreaks in multi-line equations
    text = re.sub(r"\s*\\\\\s*", r" \\\\ ", text)

    return text.strip()


def wrap_latex(expr: str | None, *, display: bool = True) -> str:
    """Normalize and wrap a LaTeX expression in appropriate delimiters ($$ or $)."""
    norm = normalize_latex(expr)
    if not norm:
        return ""
    return f"$${norm}$$" if display else f"${norm}$"
